use_frameworks!

target 'HTMICustomControl_Example' do
  pod 'HTMICustomControl', :path => '../'

  target 'HTMICustomControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
