use_frameworks!

target 'HTMICustomControl_Example' do
  pod 'HTMICustomControl', :path => '../'
  
  pod 'HTMIBaseComponent', '~> 1.1.1'
  pod 'SDCycleScrollView', '~> 1.65'

  target 'HTMICustomControl_Tests' do
    inherit! :search_paths

    
  end
end
